### PR TITLE
Update menu-firewall_adblock.txt

### PR DESCRIPTION
**Pull request by d3fz**

### CODE REVIEW

**Review by lantis1008 — APPROVED** [review]
Thanks for this, I will update Gargoyle with the same changes before the next version.

**Comment by d3fz** [comment]
No problem. In fact, i have translated the Adblock.sh page (ablock.js) to Portuguese-BR as well. I'm just not sure how to update the file.

**Comment by lantis1008** [comment]
If you like, please send me a private message on the Gargoyle forums with the changes, and I will add them.

**Comment by d3fz** [comment]
I'll do that, thank you. 

There are some other plugins that needs update/translation to the menu-"plugin_name".txt  file as well. Since they´re in the gargoyle branch, i wonder what's the best/right way to do it ?

Should i make the changes and open a pull request ? Or do you suggest something else ?

**Comment by lantis1008** [comment]
Feel free to open a pull request on the gargoyle master repository.
don't include the ones you've made to my plugins though, as i'll merge those in with my changes

**Pull request merged**
